[package]
name = "windows-drivers-util"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "Utility functions for Windows drivers"

[build-dependencies]
wdk-build = "0.4.0"

[dependencies]
wdk-sys = "0.4.0"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
